import React, { useState, useRef, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Search, MapPin, BedDouble, Bath, CarFront, Maximize, Heart, House, Menu, X, ShieldCheck, KeyRound, Handshake, Check, ChevronDown } from 'lucide-react';
import './styles.css';
import { locationGroups, matchesLocation } from './locations.js';

const photo = (id, width = 1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const properties = [
 { id: 1, name: 'Casa Jardim dos Sonhos', area: 'Lago Sul', type: 'Casa', purpose: 'Comprar', price: 1850000, beds: 3, baths: 4, cars: 2, size: 240, tag: 'Destaque', image: 'photo-1600596542815-ffad4c1539a9', description: 'Arquitetura contemporânea, ambientes integrados e um jardim para desacelerar. Uma casa cheia de luz e espaço para os seus melhores momentos.' },
 { id: 2, name: 'Apartamento Horizonte', area: 'Asa Sul', type: 'Apartamento', purpose: 'Comprar', price: 890000, beds: 2, baths: 2, cars: 1, size: 86, tag: 'Novo por aqui', image: 'photo-1600607687920-4e2a09cf159d', description: 'Um apartamento acolhedor, com sala integrada, acabamento natural e espaços que aproveitam a iluminação. Perto de tudo o que facilita sua rotina.' },
 { id: 3, name: 'Casa Refúgio Verde', area: 'Lago Norte', type: 'Casa', purpose: 'Alugar', price: 6800, beds: 3, baths: 3, cars: 2, size: 180, tag: 'Para alugar', image: 'photo-1600047509807-ba8f99d2cdde', description: 'Conforto, privacidade e natureza em harmonia. Ambientes amplos e uma área externa perfeita para aproveitar os dias com a família.' },
 { id: 4, name: 'Apartamento Essência', area: 'Asa Norte', type: 'Apartamento', purpose: 'Alugar', price: 4200, beds: 2, baths: 2, cars: 1, size: 72, tag: 'Para alugar', image: 'photo-1600210492486-724fe5c67fb0', description: 'Design acolhedor e uma localização com cafés, serviços e cultura. O espaço ideal para quem quer viver a cidade com praticidade.' },
 { id: 5, name: 'Casa Vista Serena', area: 'Lago Sul', type: 'Casa', purpose: 'Comprar', price: 2350000, beds: 4, baths: 4, cars: 3, size: 310, tag: 'Seleção Morada', image: 'photo-1600566753086-00f18fb6b3ea', description: 'Um projeto com materiais naturais, espaços generosos e integração com o verde. Conheça cada detalhe desta casa pensada para receber.' },
 { id: 6, name: 'Apartamento Aurora', area: 'Asa Sul', type: 'Apartamento', purpose: 'Comprar', price: 720000, beds: 2, baths: 1, cars: 1, size: 65, tag: 'Novo por aqui', image: 'photo-1600607687939-ce8a6c25118c', description: 'Um novo começo em um apartamento iluminado e funcional. Uma escolha para quem valoriza conforto em cada metro quadrado.' }
,
{"id":7,"name":"Casa Ipê Amarelo","area":"Jardim Botânico","type":"Casa","purpose":"Comprar","price":980000,"beds":3,"baths":3,"cars":2,"size":190,"description":"Jardim privativo, varanda coberta e ambientes integrados para aproveitar momentos em família.","tag":"Novo por aqui","image":"photo-1600596542815-ffad4c1539a9"},
{"id":8,"name":"Apartamento Parque das Águas","area":"Águas Claras","type":"Apartamento","purpose":"Comprar","price":560000,"beds":2,"baths":2,"cars":1,"size":68,"description":"Sala iluminada, varanda e dois quartos em uma planta prática para o dia a dia.","tag":"Novo por aqui","image":"photo-1600607687920-4e2a09cf159d"},
{"id":9,"name":"Casa Aconchego","area":"Guará","type":"Casa","purpose":"Alugar","price":3500,"beds":3,"baths":2,"cars":2,"size":140,"description":"Quintal, cozinha espaçosa e ambientes acolhedores para receber amigos e família.","tag":"Para alugar","image":"photo-1600047509807-ba8f99d2cdde"},
{"id":10,"name":"Apartamento Horizonte Norte","area":"Noroeste","type":"Apartamento","purpose":"Alugar","price":5800,"beds":3,"baths":3,"cars":2,"size":110,"description":"Varanda ampla, suíte e espaços integrados com acabamentos em tons naturais.","tag":"Para alugar","image":"photo-1600210492486-724fe5c67fb0"},
{"id":11,"name":"Casa Jardim Cerrado","area":"Vicente Pires","type":"Casa","purpose":"Comprar","price":850000,"beds":3,"baths":3,"cars":2,"size":210,"description":"Área externa com jardim e espaço para refeições ao ar livre, além de uma sala generosa.","tag":"Novo por aqui","image":"photo-1600566753086-00f18fb6b3ea"},
{"id":12,"name":"Apartamento Doce Lar","area":"Taguatinga","type":"Apartamento","purpose":"Alugar","price":1900,"beds":2,"baths":1,"cars":1,"size":58,"description":"Dois quartos bem distribuídos, sala confortável e cozinha funcional para uma rotina simples.","tag":"Para alugar","image":"photo-1600607687939-ce8a6c25118c"},
{"id":13,"name":"Casa Vila das Flores","area":"Sobradinho","type":"Casa","purpose":"Comprar","price":620000,"beds":3,"baths":2,"cars":2,"size":160,"description":"Uma casa térrea com varanda, quintal e espaço para criar novas memórias.","tag":"Novo por aqui","image":"photo-1600596542815-ffad4c1539a9"},
{"id":14,"name":"Apartamento Vista do Sol","area":"Samambaia","type":"Apartamento","purpose":"Comprar","price":290000,"beds":2,"baths":1,"cars":1,"size":52,"description":"Uma opção compacta e acolhedora, com dois quartos e ambientes fáceis de organizar.","tag":"Novo por aqui","image":"photo-1600607687920-4e2a09cf159d"},
{"id":15,"name":"Casa Quintal Feliz","area":"Ceilândia","type":"Casa","purpose":"Alugar","price":2200,"beds":2,"baths":2,"cars":1,"size":105,"description":"Um quintal para cultivar plantas e uma casa com ambientes funcionais e boa circulação.","tag":"Para alugar","image":"photo-1600047509807-ba8f99d2cdde"},
{"id":16,"name":"Apartamento Jardim Urbano","area":"Sudoeste","type":"Apartamento","purpose":"Comprar","price":1150000,"beds":3,"baths":3,"cars":2,"size":120,"description":"Ambientes amplos, suíte confortável e uma sala pensada para reunir quem você gosta.","tag":"Novo por aqui","image":"photo-1600210492486-724fe5c67fb0"},
{"id":17,"name":"Casa Recanto da Família","area":"Gama","type":"Casa","purpose":"Comprar","price":480000,"beds":3,"baths":2,"cars":2,"size":135,"description":"Três quartos, garagem e um espaço externo para aproveitar o seu tempo livre.","tag":"Novo por aqui","image":"photo-1600566753086-00f18fb6b3ea"},
{"id":18,"name":"Apartamento Novo Capítulo","area":"Riacho Fundo","type":"Apartamento","purpose":"Alugar","price":1600,"beds":2,"baths":1,"cars":1,"size":48,"description":"Um apartamento prático com dois quartos, ideal para começar uma nova fase.","tag":"Para alugar","image":"photo-1600607687939-ce8a6c25118c"}
];
const money = value => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(value);
function App() {
 const [menu, setMenu] = useState(false);
 const [purpose, setPurpose] = useState('Comprar');
 const [location, setLocation] = useState('');
 const [type, setType] = useState('');
 const [budget, setBudget] = useState('');
 const [filters, setFilters] = useState(null);
 const [category, setCategory] = useState('Todos');
 const [expanded, setExpanded] = useState(false);
 const [favorites, setFavorites] = useState([]);
 const [selected, setSelected] = useState(null);
 const [contact, setContact] = useState('');
 const [sent, setSent] = useState(false);
 const dialog = useRef(null);
 useEffect(() => {
   if (selected) { dialog.current.showModal(); document.body.style.overflow = 'hidden'; }
   else document.body.style.overflow = '';
   return () => { document.body.style.overflow = ''; };
 }, [selected]);
 const filtered = properties.filter(p => (!filters || (p.purpose === filters.purpose && matchesLocation(p.area, filters.location) && (!filters.type || p.type === filters.type) && (!filters.budget || p.price <= Number(filters.budget)))) && (category === 'Todos' || (category === 'Favoritos' ? favorites.includes(p.id) : p.type === category)));
 const visible = expanded ? filtered : filtered.slice(0, 6);
 const search = e => { e.preventDefault(); setFilters({ purpose, location, type, budget }); setCategory('Todos'); setExpanded(true); document.getElementById('imoveis').scrollIntoView({ behavior: 'smooth' }); };
 const inquire = p => { setContact('Olá! Tenho interesse no imóvel ' + p.name + '. Gostaria de saber mais.'); setSent(false); setSelected(null); document.getElementById('contato').scrollIntoView({ behavior: 'smooth' }); };
 return <>
 <a className="skip" href="#principal">Pular para o conteúdo</a>
 <header className="header"><div className="container nav"><a href="#" className="brand" aria-label="Morada, início"><House strokeWidth={1.7}/><span>morada<span className="brand-dot">.</span><small>IMOBILIÁRIA</small></span></a>
 <nav className={menu ? 'navigation open' : 'navigation'} aria-label="Navegação principal">{[['Início','#'],['Imóveis','#imoveis'],['Sobre nós','#sobre'],['Como funciona','#como-funciona']].map(([label,href]) => <a key={label} href={href} onClick={() => setMenu(false)}>{label}</a>)}</nav>
 <a className="button nav-contact" href="#contato">Vamos conversar <ArrowUpRight size={17}/></a><button className="menu-toggle icon-button" aria-label={menu ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div></header>
 <main id="principal">
 <section className="hero"><img className="hero-image" src={photo('photo-1600607687920-4e2a09cf159d',2200)} alt="Sala ampla e iluminada, com móveis de madeira e vista para o jardim" fetchPriority="high"/><div className="hero-shade"/>
 <div className="container hero-content"><span className="eyebrow light"><span className="tiny-line"/> MAIS QUE IMÓVEIS, NOVOS COMEÇOS</span><h1>Seu próximo capítulo<br/>começa <em>aqui.</em></h1><p>Encontre um lugar para chamar de seu.<br/>A gente cuida do caminho até lá.</p><a href="#imoveis" className="hero-link">Encontre sua morada <ArrowUpRight size={20}/></a></div><div className="hero-caption"><MapPin size={15}/> Espaços que inspiram uma nova vida</div>
 </section>
 <div className="container search-wrap"><form className="search-box" onSubmit={search}><div className="search-tabs" role="group" aria-label="Finalidade">{['Comprar','Alugar'].map(item => <button type="button" key={item} className={purpose === item ? 'active' : ''} aria-pressed={purpose === item} onClick={() => {setPurpose(item); setBudget('');}}>{item}</button>)}<span>Seu novo endereço está mais perto.</span></div><div className="search-fields">
 <label><span><MapPin size={15}/> Localização</span><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">Onde você quer morar?</option>{locationGroups.map(group=><optgroup key={group.label} label={group.label}>{group.options.map(area=><option key={area} value={area}>{area}</option>)}</optgroup>)}</select></label>
 <label><span><House size={15}/> Tipo de imóvel</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os tipos</option><option>Casa</option><option>Apartamento</option></select></label>
 <label><span>Faixa de preço</span><select value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Qualquer valor</option>{(purpose === 'Comprar' ? [800000,1000000,2000000,3000000] : [4500,6000,8000]).map(n=><option value={n} key={n}>Até {money(n)}</option>)}</select></label>
 <button className="button search-button" type="submit"><Search size={18}/> Buscar imóveis</button></div></form></div>
 <section className="container listings section" id="imoveis"><div className="section-heading"><div><span className="eyebrow">ENCONTRE O SEU LUGAR</span><h2>Novas histórias, <em>novos endereços.</em></h2><p>Uma seleção de imóveis com tudo para fazer parte da sua vida.</p></div><a href="#imoveis" className="text-link" onClick={()=>{setExpanded(true);setFilters(null);setCategory('Todos');}}>Ver todos os imóveis <ArrowUpRight size={18}/></a></div>
 <div className="listing-toolbar"><div className="pills">{['Todos','Casa','Apartamento','Favoritos'].map(c=><button key={c} className={category===c?'pill active':'pill'} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c==='Casa'?'Casas':c==='Apartamento'?'Apartamentos':c}{c==='Favoritos' && favorites.length > 0 ? ' ('+favorites.length+')' : ''}</button>)}</div>{filters && <button className="clear-filter" onClick={()=>setFilters(null)}>Limpar busca <X size={14}/></button>}</div>
 <div className="property-grid">{visible.map(p=><article className="property-card" key={p.id}><div className="property-picture"><img src={photo(p.image,800)} alt={p.name + ' — imagem ilustrativa'} loading="lazy"/><span className="property-tag">{p.tag}</span><button className={'favorite icon-button '+(favorites.includes(p.id)?'saved':'')} aria-label={(favorites.includes(p.id)?'Remover dos favoritos: ':'Favoritar: ')+p.name} aria-pressed={favorites.includes(p.id)} onClick={()=>setFavorites(f=>f.includes(p.id)?f.filter(id=>id!==p.id):[...f,p.id])}><Heart size={19} fill={favorites.includes(p.id)?'currentColor':'none'}/></button><span className="picture-type">{p.type} · {p.purpose === 'Comprar'?'Venda':'Locação'}</span></div><div className="property-info"><span className="address"><MapPin size={14}/> {p.area}, Brasília - DF</span><h3>{p.name}</h3><div className="features"><span><BedDouble size={16}/>{p.beds} quartos</span><span><Bath size={16}/>{p.baths}</span><span><CarFront size={16}/>{p.cars}</span><span><Maximize size={15}/>{p.size} m²</span></div><div className="property-bottom"><strong>{money(p.price)}{p.purpose==='Alugar'&&<small>/mês</small>}</strong><button onClick={()=>setSelected(p)} aria-label={'Ver detalhes de '+p.name}>Ver imóvel <ArrowUpRight size={17}/></button></div></div></article>)}</div>
 {visible.length === 0 && <div className="empty"><Search size={30}/><h3>{category==='Favoritos'?'Sua seleção começa com um coração.':'Vamos encontrar outra possibilidade?'}</h3><p>{category==='Favoritos'?'Toque no coração dos imóveis para salvá-los durante sua visita.':'Não há imóveis cadastrados para esta busca. Altere a localização ou os filtros.'}</p><button className="button" onClick={()=>{setCategory('Todos');setFilters(null);}}>Explorar imóveis</button></div>}
 {!expanded && filtered.length>6 && <button className="more-button" onClick={()=>setExpanded(true)}>Explorar mais imóveis <ArrowRight size={17}/></button>}
 <p className="demo-note">Imóveis e valores ilustrativos para projeto acadêmico.</p></section>
 <section id="sobre" className="about"><div className="container about-layout"><div className="about-visual"><img src={photo('photo-1600210492486-724fe5c67fb0',1000)} loading="lazy" alt="Ambiente acolhedor com sofá, plantas e iluminação natural"/><div className="image-note"><House size={29}/><span>Um lugar.<br/><strong>Infinitas possibilidades.</strong></span></div></div><div className="about-copy"><span className="eyebrow">MUITO PRAZER, SOMOS A MORADA</span><h2>Imóveis são espaços.<br/><em>Lares são conexões.</em></h2><p>Acreditamos que encontrar um imóvel é encontrar o cenário da sua próxima história. Por isso, colocamos suas escolhas, seus planos e seu jeito de viver no centro de tudo.</p><p>Do primeiro olhar à entrega das chaves, nossa proposta é tornar cada etapa mais simples, próxima e transparente.</p><a className="text-link" href="#contato">Conheça a gente <ArrowUpRight size={18}/></a><div className="about-values"><span><ShieldCheck size={23}/>Transparência<br/>em cada detalhe</span><span><Handshake size={23}/>Atendimento<br/>de pessoa para pessoa</span></div></div></div></section>
 <section className="container section steps" id="como-funciona"><span className="eyebrow">DO SEU JEITO, NO SEU TEMPO</span><h2>O caminho para sua <em>nova morada.</em></h2><div className="steps-grid">{[{n:'01',Icon:Search,title:'Encontre suas possibilidades',text:'Explore os imóveis e filtre o que faz sentido para o seu momento.'},{n:'02',Icon:Handshake,title:'Converse e conheça de perto',text:'Conte seus planos e escolha os imóveis que você gostaria de visitar.'},{n:'03',Icon:KeyRound,title:'Comece um novo capítulo',text:'Com orientação em cada etapa, o próximo endereço fica mais perto.'}].map(({n,Icon,title,text})=><div className="step" key={n}><div className="step-top"><Icon size={26} strokeWidth={1.5}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></div>)}</div></section>
 <section className="contact-section" id="contato"><div className="container contact-layout"><div><span className="eyebrow light">VAMOS ENCONTRAR SEU NOVO ENDEREÇO?</span><h2>Todo novo começo<br/>parte de uma <em>conversa.</em></h2><p>Conte o que você procura.<br/>Seu próximo capítulo pode começar por aqui.</p><span className="contact-note"><Check size={17}/> Você no centro de cada escolha.</span></div><form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true);}}><label>Seu nome<input required name="name" autoComplete="name" placeholder="Como podemos chamar você?" maxLength={100}/></label><label>E-mail<input required type="email" name="email" autoComplete="email" placeholder="voce@exemplo.com" maxLength={180}/></label><label>O que você procura?<textarea required name="message" rows={3} value={contact} onChange={e=>{setContact(e.target.value);setSent(false);}} placeholder="Conte um pouco sobre a sua próxima morada..." maxLength={1500}/></label><button className="button" type="submit">Simular contato <ArrowUpRight size={18}/></button><p className="form-note">Demonstração acadêmica: os dados não são enviados ou armazenados.</p>{sent&&<p className="success" role="status"><Check size={18}/> Simulação concluída! Em um site real, sua mensagem seria encaminhada à equipe.</p>}</form></div></section>
 </main><footer><div className="container footer-top"><a href="#" className="brand"><House strokeWidth={1.7}/><span>morada.<small>IMOBILIÁRIA</small></span></a><p>Mais que um endereço.<br/>Um lugar para viver sua história.</p><a href="#imoveis">Encontre sua morada <ArrowUpRight size={17}/></a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Morada · Projeto acadêmico em React.</span><span>Marca fictícia · Fotografias: Unsplash</span><a href="#">Voltar ao topo ↑</a></div></footer>
 <dialog ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null);}} onClose={()=>setSelected(null)} aria-labelledby="detail-title">{selected && <><button className="dialog-close icon-button" aria-label="Fechar detalhes" onClick={()=>setSelected(null)} autoFocus><X/></button><img className="dialog-image" src={photo(selected.image)} alt={selected.name}/><div className="dialog-body"><span className="eyebrow">{selected.type} · {selected.purpose==='Comprar'?'À venda':'Para alugar'}</span><h2 id="detail-title">{selected.name}</h2><p className="address"><MapPin size={16}/>{selected.area}, Brasília - DF</p><p>{selected.description}</p><div className="dialog-features">{selected.beds} quartos · {selected.baths} banheiros · {selected.cars} vagas · {selected.size} m²</div><strong className="dialog-price">{money(selected.price)}{selected.purpose==='Alugar'?'/mês':''}</strong><button className="button" onClick={()=>inquire(selected)}>Tenho interesse <ArrowUpRight size={18}/></button><small>Imóvel fictício. Fotografia ilustrativa.</small></div></>}</dialog>
 </>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
